version: "3"

services:
  web:
    image: webdevops/php-apache:7.4-alpine
    ports:
      - "8090:80"
    environment: 
      WEB_DOCUMENT_ROOT: /app/public  
    volumes:
      - ./:/app
    links: 
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: INNOUT