version: "3"

services:
  web:
    image: webdevops/php-apache:7.4-alpine
    ports:
      - "8090:80"
    volumes:
      - ./:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8089:80"